### ISSUE TITLE
Handling number 0 in translate _replaceData

### ISSUE THREAD

**Issue by jlmessenger** [noveogroup-amorgunov/localizify#3]
Translating with a data parameter of value 0 does not get output as expected.

test case: `t('Likes: {count}', { count: 0 })`
expected: `Likes: 0`
actual: `Likes: {count}`

I chased this down to the `_replaceData` function using `||` for fallback handling.
This makes sense to prevent `null` or `undefined` values in the output, but as `0` is also interpreted as false, it falls-thru as-well.

`const replaceTo = data[term] || this.getStore().interpolations[term] || _term;`
https://github.com/noveogroup-amorgunov/localizify/blob/master/src/localizify.js#L180

Possible solution, simply check for `0` and allow it thru.
```js
// find first useful value, or default to last value
function coalesce(...values) {
  const foundIdx = values.findIndex(value => value === 0 || value);
  return foundIdx > -1 ? values[foundIdx] : values[values.length - 1];
}

const replaceTo = firstValue(data[term], this.getStore().interpolations[term], _term);
```

Of course there exists a similar limitation for `false`, and objects getting output as `[object Object]`, so the check could be made specific to types:
```
// allow non-empty string, and any number or boolean
// disallow object, array, null, undefined
function acceptedType(value) {
  return value !== '' && ['string', 'number', 'boolean'].includes(typeof value);
}
function coalesce(...values) {
  const foundIdx = values.findIndex(acceptedType);
  return foundIdx > -1 ? values[foundIdx] : values[values.length - 1];
}
```

**Comment by noveogroup-amorgunov** [comment]
@jlmessenger Good catch! Case with 0 fixed in #4 I fixed this behavior for all negative cases except undefined.

What about objects I think the user should be responsible for this. If he wants to pass object (maybe object has overwrite toString method), he should be able to do it.
